apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  otel-collector-config: |
    receivers:
      fluentforward:
        endpoint: 0.0.0.0:8006
      
      collectd:
        timeout: "50s"
        endpoint: 0.0.0.0:8007

    processors:
      batch:
      memory_limiter:
        # 80% of maximum memory up to 2G
        limit_mib: 1500
        # 25% of limit up to 2G
        spike_limit_mib: 512
        check_interval: 5s

    extensions:

      zpages: {}

      memory_ballast:
        # Memory Ballast size should be max 1/3 to 1/2 of memory.
        size_mib: 683

    exporters:


      kafka/fluent:
        protocol_version: 2.0.0
        brokers: kafka-broker-svc:9092
        topic: otel.fluent
        auth:
          tls:
            ca_file: /certs/ca.crt
            cert_file: /certs/kafka-cert.pem
            key_file: /certs/kafka-key.pem
        encoding: otlp_json
      
      kafka/collectd:
        protocol_version: 2.0.0
        brokers: kafka-broker-svc:9092
        topic: otel.collectd
        auth:
          tls:
            ca_file: /certs/ca.crt
            cert_file: /certs/kafka-cert.pem
            key_file: /certs/kafka-key.pem
        encoding: otlp_json
      
      elasticsearch:
        endpoints:
        - "https://logsdb-svc:9200"
        index: logstash-otel
        tls:
          ca_file: /certs/ca.crt
          cert_file: /certs/fluentbit-cert.pem
          key_file: /certs/fluentbit-key.pem


    service:
      extensions: [zpages, memory_ballast]
      pipelines:
        logs:
          receivers: [fluentforward]
          processors: [memory_limiter, batch]
          exporters: [kafka/fluent, elasticsearch]
        metrics:
          receivers: [collectd]
          processors: [memory_limiter, batch]
          exporters: [kafka/collectd]
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  ports:
  - name: fluent-http # Default endpoint for OpenTelemetry gRPC receiver.
    port: 8006
    protocol: TCP
    targetPort: 8006
  - name: collectd-https # Default endpoint for OpenTelemetry gRPC receiver.
    port: 8007
    protocol: TCP
    targetPort: 8007
  - name: metrics # Default endpoint for querying metrics.
    port: 8888
  selector:
    component: otel-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 3 #TODO - adjust this to your own requirements
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      containers:
      - image: otel/opentelemetry-collector-contrib:0.48.0
        name: otel-collector
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi
        ports:
        - containerPort: 55679 # Default endpoint for ZPages.
        - containerPort: 9411 # Default endpoint for Zipkin receiver.
        - containerPort: 8888  # Default endpoint for querying metrics.
        - containerPort: 8006  # fluent.
        - containerPort: 8007  # collectd.
        volumeMounts:
        - name: otel-collector-config-vol
          mountPath: /etc/otelcol-contrib
        - name: otel-cluster-config-vol
          mountPath: /certs
      volumes:
        - configMap:
            name: otel-collector-conf
            items:
              - key: otel-collector-config
                path: config.yaml
          name: otel-collector-config-vol
        - configMap:
            name: otel-cluster-config
            items:
              - key: ca.crt
                path: ca.crt
              - key: kafka-cert.pem
                path: kafka-cert.pem
              - key: kafka-key.pem
                path: kafka-key.pem
              - key: fluentbit-cert.pem
                path: fluentbit-cert.pem
              - key: fluentbit-key.pem
                path: fluentbit-key.pem
          name: otel-cluster-config-vol